import puppeteer from 'puppeteer-core';
const BASE = 'http://localhost:8080/ag_salao/';
const API = 'http://localhost:8080/ag_salao/api';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const r = await fetch(`${API}/appointments`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ serviceId: 'srv-2', serviceName: 'Corte Feminino', servicePrice: 90, serviceDuration: 50, professionalId: 'prof-2', professionalName: 'Camila Rocha', date: '2026-08-14', time: '11:00', clientName: 'Fernanda Silva', clientPhone: '11966665555', clientEmail: 'fe@x.com', status: 'confirmed' }) });
const a = await r.json();
const browser = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome-stable', headless: 'new', args: ['--no-sandbox', '--disable-setuid-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 900, height: 1000 });
await page.goto(BASE, { waitUntil: 'networkidle0' });
await sleep(500);
await page.evaluate(() => { const b = [...document.querySelectorAll('button')].find((x) => /Consultar \/ Cancelar/i.test(x.textContent || '')); if (b) b.click(); });
await sleep(400);
await page.evaluate((code, phone) => { const set = (el, v) => { const s = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set; s.call(el, v); el.dispatchEvent(new Event('input', { bubbles: true })); }; const i = document.querySelectorAll('input'); set(i[0], code); set(i[1], phone); }, a.code, '11966665555');
await page.evaluate(() => { const b = [...document.querySelectorAll('button')].find((x) => (x.textContent || '').trim() === 'Consultar'); if (b) b.click(); });
await sleep(900);
await page.screenshot({ path: '/opt/cursor/artifacts/ag_salao_meu_agendamento.png' });
await browser.close();
console.log('shot ok:', a.code);
